config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  root "addresses#index"

  devise_for :users, class_name: "FormUser",
    controllers: {omniauth_callbacks: "omniauth_callbacks",
                  registrations: "registrations"}

  devise_scope :user do
    get "/users/auth/:provider/upgrade" => "omniauth_callbacks#upgrade",
      as: :user_omniauth_upgrade
    get "/users/auth/:provider/setup", to: "omniauth_callbacks#setup"
  end

  resources :addresses do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :reviews, only: :none do
    resources :comments, except: [:show, :new]
  end

  resources :searchs, only: :index
  resources :maps, only: :show
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  include RailsAdmin::User

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :omniauthable
  has_many :addresses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :identities
  has_many :chats

  enum role: [:normal, :admin]

  mount_uploader :avatar, PhotoUploader

  PARAMS_ATTRIBUTES = [:name, :email, :password, :password_confirmation,
    :current_password, :avatar]

  def google_oauth2
    identities.where(provider: "google_oauth2").first
  end

  def google_oauth2_client
    unless @google_oauth2_client
      @google_oauth2_client = Google::APIClient
        .new application_name: "omniauth-google-oauth2"
      @google_oauth2_client.authorization
        .update_token!({access_token: google_oauth2.accesstoken,
        refresh_token: google_oauth2.refreshtoken})
    end
    @google_oauth2_client
  end

  def facebook
    identities.find_by provider: Settings.provider.facebook
  end

  def facebook_client
    @facebook_client ||= Facebook.client access_token: facebook.accesstoken
  end

  def twitter
    identities.find_by provider: Settings.provider.twitter
  end

  def twitter_client
    @twitter_client ||= Twitter.client access_token: twitter.accesstoken
  end

  def linkedin
    identities.find_by provider: Settings.provider.linkedin
  end

  def linkedin_client
    @linkdin_client ||= Linkedin.client access_token: linkedin.accesstoken
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
    @form_user = FormUser.find params[:id]
    @sort = params[:type]
    @addresses = if @sort.blank?
      @user.addresses.page params[:page]
    else
      @user.addresses.order_by_colunm(@sort["type"]).page params[:page]
    end
  end
end

app/views/users/shared/_links.html.erb
<div class="col-md-offset-3">
  <br />
  <% if controller_name != "sessions" %>
    <%= link_to t("login"), new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != "registrations" %>
    <%= link_to t("sign_up"), new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != "passwords" &&
    controller_name != "registrations" %>
      <%= link_to t("forgot_password"), new_password_path(resource_name) %>
      <br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != "confirmations" %>
    <%= link_to t("confirm_instructions"),
      new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? &&
    resource_class.unlock_strategy_enabled?(:email) &&
    controller_name != "unlocks" %>
      <%= link_to t("unlock_instructions"), new_unlock_path(resource_name) %>
      <br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to t("Sign in with #{provider.to_s.titleize}"),
        omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>