config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  root "addresses#index"

  devise_for :users, class_name: "FormUser",
    controllers: {omniauth_callbacks: "omniauth_callbacks",
                  registrations: "registrations"}

  devise_scope :user do
    get "/users/auth/:provider/upgrade" => "omniauth_callbacks#upgrade",
      as: :user_omniauth_upgrade
    get "/users/auth/:provider/setup", to: "omniauth_callbacks#setup"
  end

  resources :addresses do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :reviews, only: :none do
    resources :comments, except: [:show, :new]
  end

  resources :searchs, only: :index
  resources :maps, only: :show
  resources :users
end

app/views/shared/_chat_dialog.html.erb
<div id="chat-info" class="chat-box">
  <div id="chat-dialog" class="row chat-box-div">
    <div id="chat-head" class="col-md-12 chat-box-head">
      <%= t "chat.head" %>
      <div class="btn-group chat-dialog-btn">
        <div id="chat-dialog-btn" class="fa fa-angle-double-up"></div>
      </div>
    </div>
    <div id="message-history-chat" class="col-md-12 panel-body chat-box-main">
    </div>
    <div id="chat-footer" class="chat-box-footer">
      <div class="input-group">
        <input type="text" class="form-control" id="message-input-field">
        <span class="input-group-btn">
          <button id="chat-send-btn" class="btn btn-info" type="button"><%= t "chat.send" %></button>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_condition_field.html.erb
<div class="search">
    <div class="row">
      <div class="col-sm-8">
        <div class="col-sm-6">
          <%= f.label :square %>
          <%= f.collection_select :square_gteq, Settings.squares,
            :last, :first, {include_blank: t("search.minimum")},
            {class: "form-control", id: "min_square"} %><br>
          <%= f.collection_select :square_lteq, Settings.squares,
            :last, :first, {include_blank: t("search.maximum")},
            {class: "form-control", id: "max_square"} %>
        </div>
        <div class="col-sm-6">
          <%= f.label :price %>
          <%= f.collection_select :price_gteq, Settings.prices,
            :last, :first, {include_blank: t("search.minimum")},
            {class: "form-control", id: "min_price"} %><br>
          <%= f.collection_select :price_lteq, Settings.prices,
            :last, :first, {include_blank: t("search.maximum")},
            {class: "form-control", id: "max_price"} %><br>
        </div>
      </div>
      <div class="col-sm-4">
        <%= f.label :region_province %>
        <%= f.collection_select :region_province_cont, Settings.locations,
          :last, :last, {include_blank: t("search.region")},
          {class: "form-control", id: "address"} %><br>
        <%= link_to t("description.advance_search"), "javascript:void(0)",
          id: "advance_search" %>
      </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div class="wall">
        <%= f.text_field :description_or_title_cont, {placeholder: t("search.keyword"),
          class: "form-control", id: "keyword"} %>
      </div>
    </div>
    <div class="col-sm-4">
      <%= f.submit t("api.search"), {class: "btn btn-primary btn-block",
        id: "sumbit_search"} %>
    </div>
  </div><br>
  <%= render "searchs/advance_search", f: f %>
</div><br>

app/views/shared/_current_location.html.erb
<div id="mylocation">
  <%= image_submit_tag "mylocal.png" %>
  <div class="info">
    <h4><%= t "api.local" %></h4>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error.form_contain" %>
      <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li class="error-messages"><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_filter.html.erb
<%= search_form_for @search, url: searchs_path do |f| %>
  <%= render "shared/condition_field", f: f %>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
  <div class="container">
    <% Menu.bottom.roots.each do |root| %>
      <div class="col-md-3">
        <h4><%= link_to root.name, root.url %></h4>
        <% if root.has_children? %>
          <% root.children.each do |children| %>
            <li><%= link_to children.name, children.url %></li>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<footer>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="my-header">
  <div class="container">
    <div><%= link_to t("layouts.banner"), root_path, id: "logo" %></div>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t("layouts.home"), root_path %></li>
          <% if current_user.nil? %>
            <li><%= link_to t("login"), new_user_session_path %></li>
            <li><%= link_to t("register"), new_user_registration_path %></li>
          <% else %>
            <li><%= link_to t("address.add_new_address"), new_address_path %></li>
            <li id="fat-menu" class="dropdown header_user">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <% if current_user.avatar.present? %>
                  <%= image_tag current_user.avatar.url, class: "img-circle",
                    id: "fix_avatar_on_header" %>
                <% else %>
                  <%= image_tag Settings.user.avatar_default, class: "img-circle", 
                    id: "fix_avatar_on_header" %>
                <% end %>
              <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to t("layouts.profile"), user_path(current_user) %></li>
                <li>
                  <%= link_to t("layouts.setting"), edit_user_registration_path(current_user) %>
                </li>
                <li>
                  <%= link_to t("logout"), destroy_user_session_path,
                  method: :delete %>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_navbar.html.erb
<ul id="sample-menu-1" class="sf-menu">
  <% Menu.top.roots.each do |root| %>
    <li>
      <%= link_to root.name, root.url %>
        <% if root.has_children? %>
          <ul>
            <% root.children.each do |children| %>
              <li><%= link_to children.name, children.url %></li>
            <% end %>
          </ul>
        <% end %>
    </li>
  <% end %>
</ul>

app/views/shared/_search.html.erb
<div id="search">
  <%= form_tag("/search", method: "get") do %>
    <%= text_field_tag "Search", nil, class: "search_field",
      placeholder: t("api.holder") %>
    <%= submit_tag t("api.search"), class: "search_button" %>
  <% end %>
</div>