config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  root "addresses#index"

  devise_for :users, class_name: "FormUser",
    controllers: {omniauth_callbacks: "omniauth_callbacks",
                  registrations: "registrations"}

  devise_scope :user do
    get "/users/auth/:provider/upgrade" => "omniauth_callbacks#upgrade",
      as: :user_omniauth_upgrade
    get "/users/auth/:provider/setup", to: "omniauth_callbacks#setup"
  end

  resources :addresses do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end

  resources :reviews, only: :none do
    resources :comments, except: [:show, :new]
  end

  resources :searchs, only: :index
  resources :maps, only: :show
  resources :users
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_address
  before_action :find_review, except: :create

  respond_to :js

  def create
    @review = @address.reviews.build review_params
    @review.user = current_user
    @review.save
  end

  def edit
  end

  def update
    @review.update_attributes review_params
  end

  def destroy
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit :content, :image, :point
  end

  def find_address
    @address = Address.find params[:address_id]
  end

  def find_review
    @review = @address.reviews.find params[:id]
  end
end

app/views/reviews/_form.html.erb
<%= form_for [@address, @review], html: {multipart: true}, remote: true do |f| %>
  <div class="text-area-wrapper">
    <%= f.text_area :content, class: "form-control",
                              placeholder: t("review.placeholder") %>
    <%= f.hidden_field :point, value: "" %>
  </div>
  <div class="post-action">
    <section class="upload-img">
      <%= image_tag Settings.review.upload_icon, title: t("review.upload_title") %>
      <%= f.file_field :image, id: "choose-file" %>
    </section>
    <section class="rate-address">
      <div id="rate"></div>
    </section>
    <section class="form-actions">
      <%= f.submit class: "btn btn-success" %>
    </section>
    <div class="clearfix"></div>
    <p id="selected-file-name"></p>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<% if review.user %>
  <li id="<%= dom_id review %>" class="review">
    <div class="row">
      <div class="col-md-1">
        <%= link_to_avatar review.user %>
      </div>
      <div class="col-md-11">
        <div class="wrap-content-review">
          <strong>
            <%= link_to review.user.name, user_path(id: review.user.id), class: "user_name" %>
          </strong>
          <span>
            <%= time_ago_in_words review.created_at %> <%= t "review.ago" %>
          </span>
          <div class="show-point" data-rate="<%= review.point %>"></div>
          <div class="image-review">
            <%= image_tag review.image.url if review.image.present? %>
          </div>
          <div class="review-content">
            <%= review.content %>
          </div>
          <div class="list-features">
            <%= link_to t("edit"), [:edit, @address, review], remote: true if can? :update, review %>
            <%= link_to t("delete"), address_review_path(@address, review),
              method: :delete, data: {confirm: t("you_sure")},
                remote: true if can? :destroy, review %>
            <%= link_to_count_comments review %>
          </div>
          <div class="form-add-comment">
          </div>
          <div class="comment-list"></div>
        </div>
      </div>
    </div>
    <div class="icon-colspan">
      <i class="glyphicon glyphicon-menu-up" title="hide"></i><br>
      <i class="glyphicon glyphicon-menu-down" title="show"></i>
    </div>
  </li>
<% end %>

app/views/reviews/create.js.erb
$("#review-list").append("<%= j render @review %>")
$(".icon-colspan i:last-child").hide()
$("#review_content").val("")

$("#show-score").raty({
  readOnly: true,
  score: <%= @review.address.average_point %>
})

$("#show-score+span").text("(<%= pluralize @review.address.reviews.count,
                                 t('review.vote') %>)")

$("#review-number").text("<%= pluralize @review.address.reviews.count,
                              t('review.review_label') %>")

$("#rate").raty({score: 0})
$("#selected-file-name").text("")
$(".form-actions").css("padding-top", "0px")
$("#review_point").val("")

$(".rate-address #rate img").click(function(){
  $("#review_point").val($(".rate-address #rate input").val())
})

$("#choose-file").change(function(){
  $("#selected-file-name").text($(this).val())
  $(".form-actions").css("padding-top", "8px")
})

$("#review_<%= @review.id %> .show-point").raty({
  readOnly: true,
  score: <%= @review.point %>
});

app/views/reviews/destroy.js.erb
$("#review_<%= @review.id %>").remove()
$("#review-number").text("<%= pluralize @review.address.reviews.count, t('review.review_label') %>")
$("#show-score + span").text("(<%= pluralize @review.address.reviews.count, t('review.vote') %>)")
$(".icon-colspan i:last-child").hide()

app/views/reviews/edit.js.erb
$("#review_<%= @review.id %>").append("<div><%= j render("form") %></div>")

$("#review_<%= @review.id %> #rate").raty({
  score: <%= @review.point %>,
  half: true,
  click: function(score, evt) {
    $("#review_<%= @review.id %> #review_point").val(score)
  }
})
$("#review_<%= @review.id %> .list-features a").first().css("color", "#2e9fff")

$("#review_<%= @review.id %> .list-features a").click(function(){
  if($("#review_<%= @review.id %> .edit_review").length > 0){
    return false;
  }
});

$("<section><button type='button' class='btn btn-default cancel'>Cancel</button></section>").insertAfter($("#review_<%= @review.id %> .rate-address"))
$("#review_<%= @review.id %> #review_point").val("<%= @review.point %>")
$("#review_<%= @review.id %> #choose-file").hide()

$("#review_<%= @review.id %> .upload-img img").click(function(){
  $("#review_<%= @review.id %> #choose-file").click();
})

$("#review_<%= @review.id %> #choose-file").change(function(){
  $("#review_<%= @review.id %> #selected-file-name").text($(this).val())
  $("#review_<%= @review.id %> input[type='submit'], #review_<%= @review.id %> button.cancel").css("margin-top", "8px")
})

$("button.cancel").click(function(){
  $(this).closest(".edit_review").remove()
  $("#review_<%= @review.id %> .list-features a").first().css("color", "rgba(0, 39, 59, 0.35)")
})

app/views/reviews/update.js.erb
<% if @review.errors.any? %>
  alert("<%= raw @review.errors.full_messages.join("\n") %>")
<% else %>
  $("#edit_review<%= @review.id %>").remove()
  $("#review_<%= @review.id %>").html("<%= j render @review %>")
  $("#review_<%= @review.id %>").css("margin-left", "0px")
  $(".icon-colspan i:last-child").hide()
  $("#review_<%= @review.id %> .list-features a").first().css("color", "rgba(0, 39, 59, 0.35)")
  $("#show-score").raty({
    readOnly: true,
    score: <%= @review.address.average_point %>
  })

  $("#review_<%= @review.id %> .show-point").raty({
    readOnly: true,
    score: <%= @review.point %>
  });
<% end %>